name: Eureka Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Copy about deploy files
        run: |
          rm -rf ./scp
          mkdir scp
          mkdir scp/resources
          cp $(ls ./build/libs/*.jar | grep -v "plain") ./scp
          cp ./src/main/resources/*.yml ./scp/resources

      - name: Copy to EC2
        run: scp -i ${{ secrets.PEM_KEY }} -r ./scp ec2-user@${{ secrets.EUREKA_HOST }}:/home/ec2-user/

      - name: Connect and deploy
        run: ssh eureka "./deploy/deploy.sh; exit"