name: Eureka Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image & Deploy
        run: |
          if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
            TAG="dev"
          elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            TAG="prod"
          fi
          
          echo TAG = $TAG
          
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_EUREKA }}:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_EUREKA }}:$TAG
          
          kubectl rollout restart deployment/orca-eureka-$TAG
          kubectl rollout status deployment/orca-eureka-$TAG